# YAML Linting Configuration for Diabetes Prediction MLOps Project

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: -1
    level: error
  commas:
    max-spaces-after: -1
    level: error
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    max: 3
    level: error
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  float-values: disable
  hyphens:
    max-spaces-after: 1
    level: error
  indentation:
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  key-ordering: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
  new-line-at-end-of-file: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  truthy: disable